VIDEO_PATH="dataset/video/s_8.mp4"
OUTPUT_VIDEO_PATH="hasil/s_8.mp4"
WATER_GAUGE_THRESHOLD=0.6
NUMBER_OBJECT_DETECTION_THRESHOLD=0.6
WATER_SEGMENTATION_THRESHOLD=0.7
WATER_GAUGE_HEIGHT=350

MODEL_WATER_GAUGE="models/water_gauge.pt"
MODEL_NUMBER="models/number.pt"
MODEL_WATER_SEGMENTATION="models/water_seg.pt"